require("dotenv").config();
const { GoogleGenAI } = require("@google/genai");

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

/**
 * Sends a prompt to Gemini and returns the AI response.
 */
async function geminiResponse(prompt) {
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: [{ role: "user", parts: [{ text: prompt }] }]
    });

    return response;
}

/**
 * Creates a human-friendly summary of the transcript.
 */
async function summarizeText(transcript) {
    const prompt = `Here is the audio transcription: ${transcript}

Please generate a clear, human-friendly summary based on the above audio transcription. The summary should highlight key points, central ideas, and any emotionally impactful or meaningful statements. Ensure the tone feels natural and thoughtful—like it was written by a person, not generated by an AI system.

The summary must be written in paragraph form.

Use the following exact format in your response:
Here is the summary of the given audio file:  \n\n
The audio file is about [your summary here]
`;

    try {
        const response = await geminiResponse(prompt);
        const result = response.text;
        return result;
    } catch (error) {
        console.error("Error calling Gemini API:", error.message);
        throw error;
    }
}

/**
 * Improves the summary by making it more natural and emotionally engaging.
 */
async function reSummarizeText(initialSummary) {
    const prompt = `Here is the initial summary of the audio transcription: ${initialSummary}

Please re-summarize this text to make it more concise, emotionally engaging, and human-sounding. Focus on keeping the core message and emotional tone intact, but improve clarity, flow, and naturalness. Avoid sounding robotic or generic.

The re-summarized version should be written in paragraph form.

Use the following exact format in your response:
Here is the improved summary of the given audio file: \n\n
The audio file is about [your improved summary here]
`;

    try {
        const response = await geminiResponse(prompt);
        const result = response.text;
        return result;
    } catch (error) {
        console.error("Error calling Gemini API:", error.message);
        throw error;
    }
}

module.exports = { summarizeText, reSummarizeText };
